stages:
  - run_image
  - build
  - test

runImage:
  stage: run_image
  script:
    - docker-compose build
    - docker-compose push
  #  only:
  #    changes:
  #      - Dockerfile
  when: manual
  tags:
    - devel-39

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  only:
    - devel
  when: manual

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
  only:
    - devel
  when: manual

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
  only:
    - devel
  when: manual