image: ardiwahyu/android:28.0.3

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - chmod +x ./gradlew

stages:
  - build
  - test

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint
  only:
    - devel
  when: manual

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/
  only:
    - devel
  when: manual

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug
  only:
    - devel
  when: manual